services:
  postgres:
    image: postgres:16-alpine
    container_name: chi_tieu_gd_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-chi_tieu_gd_dev}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    env_file:
      - .env.dev
    depends_on:
      - postgres

  migrator:
    env_file:
      - .env.dev
    depends_on:
      - postgres

volumes:
  postgres_data: