services:
  postgres:
    image: postgres:16-alpine
    container_name: chi_tieu_gd_postgres
    restart: unless-stopped
    shm_size: 256mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB:-chi_tieu_gd_dev}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-chi_tieu_gd_dev}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  migrator:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder # Điểm ăn tiền: Chỉ build tới stage 'builder' để có sẵn drizzle-kit
    container_name: chi_tieu_gd_migrator
    env_file:
      - .env
    # Chạy lệnh push schema của Drizzle
    command: >
      sh -c "
      if [ \"$NODE_ENV\" = 'production' ]; then
      echo 'Running migration (PROD)';
      pnpm run db:mi;
      else
      echo 'Running db push (DEV)';
      pnpm run db:push;
       fi
      "
    depends_on:
      postgres:
        condition: service_healthy # Phải đợi DB khỏe mạnh mới được push

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chi_tieu_gd_api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      migrator:
        condition: service_completed_successfully

  nginx:
    image: nginx:1.27-alpine
    container_name: chi_tieu_gd_nginx
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api

volumes:
  postgres_data:
    name: chi_tieu_gd_postgres_data